package com.lanou.entity;

import java.math.BigDecimal;

public class Kmcjb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmcjb_$kmid$.id
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmcjb_$kmid$.xjh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String xjh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmcjb_$kmid$.kh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String kh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmcjb_$kmid$.xm
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String xm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmcjb_$kmid$.jsmc
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String jsmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmcjb_$kmid$.ablx
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String ablx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmcjb_$kmid$.bth
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String bth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmcjb_$kmid$.fth
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String fth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmcjb_$kmid$.kg
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private BigDecimal kg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmcjb_$kmid$.zg
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private BigDecimal zg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmcjb_$kmid$.zf
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private BigDecimal zf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmcjb_$kmid$.kmid
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private Integer kmid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmcjb_$kmid$.id
	 * @return  the value of kmcjb_$kmid$.id
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmcjb_$kmid$.id
	 * @param id  the value for kmcjb_$kmid$.id
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmcjb_$kmid$.xjh
	 * @return  the value of kmcjb_$kmid$.xjh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getXjh() {
		return xjh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmcjb_$kmid$.xjh
	 * @param xjh  the value for kmcjb_$kmid$.xjh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setXjh(String xjh) {
		this.xjh = xjh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmcjb_$kmid$.kh
	 * @return  the value of kmcjb_$kmid$.kh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getKh() {
		return kh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmcjb_$kmid$.kh
	 * @param kh  the value for kmcjb_$kmid$.kh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setKh(String kh) {
		this.kh = kh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmcjb_$kmid$.xm
	 * @return  the value of kmcjb_$kmid$.xm
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getXm() {
		return xm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmcjb_$kmid$.xm
	 * @param xm  the value for kmcjb_$kmid$.xm
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setXm(String xm) {
		this.xm = xm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmcjb_$kmid$.jsmc
	 * @return  the value of kmcjb_$kmid$.jsmc
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getJsmc() {
		return jsmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmcjb_$kmid$.jsmc
	 * @param jsmc  the value for kmcjb_$kmid$.jsmc
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setJsmc(String jsmc) {
		this.jsmc = jsmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmcjb_$kmid$.ablx
	 * @return  the value of kmcjb_$kmid$.ablx
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getAblx() {
		return ablx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmcjb_$kmid$.ablx
	 * @param ablx  the value for kmcjb_$kmid$.ablx
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setAblx(String ablx) {
		this.ablx = ablx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmcjb_$kmid$.bth
	 * @return  the value of kmcjb_$kmid$.bth
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getBth() {
		return bth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmcjb_$kmid$.bth
	 * @param bth  the value for kmcjb_$kmid$.bth
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setBth(String bth) {
		this.bth = bth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmcjb_$kmid$.fth
	 * @return  the value of kmcjb_$kmid$.fth
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getFth() {
		return fth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmcjb_$kmid$.fth
	 * @param fth  the value for kmcjb_$kmid$.fth
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setFth(String fth) {
		this.fth = fth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmcjb_$kmid$.kg
	 * @return  the value of kmcjb_$kmid$.kg
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public BigDecimal getKg() {
		return kg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmcjb_$kmid$.kg
	 * @param kg  the value for kmcjb_$kmid$.kg
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setKg(BigDecimal kg) {
		this.kg = kg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmcjb_$kmid$.zg
	 * @return  the value of kmcjb_$kmid$.zg
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public BigDecimal getZg() {
		return zg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmcjb_$kmid$.zg
	 * @param zg  the value for kmcjb_$kmid$.zg
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setZg(BigDecimal zg) {
		this.zg = zg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmcjb_$kmid$.zf
	 * @return  the value of kmcjb_$kmid$.zf
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public BigDecimal getZf() {
		return zf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmcjb_$kmid$.zf
	 * @param zf  the value for kmcjb_$kmid$.zf
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setZf(BigDecimal zf) {
		this.zf = zf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmcjb_$kmid$.kmid
	 * @return  the value of kmcjb_$kmid$.kmid
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public Integer getKmid() {
		return kmid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmcjb_$kmid$.kmid
	 * @param kmid  the value for kmcjb_$kmid$.kmid
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setKmid(Integer kmid) {
		this.kmid = kmid;
	}
}