package com.lanou.entity;

import java.math.BigDecimal;

public class Kmffb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmffb_$kmid$.id
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmffb_$kmid$.xjh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String xjh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmffb_$kmid$.kh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String kh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmffb_$kmid$.xm
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String xm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmffb_$kmid$.jsmc
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String jsmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmffb_$kmid$.ablx
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String ablx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmffb_$kmid$.ysf
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private BigDecimal ysf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmffb_$kmid$.ff
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private BigDecimal ff;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kmffb_$kmid$.kmid
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private Integer kmid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmffb_$kmid$.id
	 * @return  the value of kmffb_$kmid$.id
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmffb_$kmid$.id
	 * @param id  the value for kmffb_$kmid$.id
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmffb_$kmid$.xjh
	 * @return  the value of kmffb_$kmid$.xjh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getXjh() {
		return xjh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmffb_$kmid$.xjh
	 * @param xjh  the value for kmffb_$kmid$.xjh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setXjh(String xjh) {
		this.xjh = xjh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmffb_$kmid$.kh
	 * @return  the value of kmffb_$kmid$.kh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getKh() {
		return kh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmffb_$kmid$.kh
	 * @param kh  the value for kmffb_$kmid$.kh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setKh(String kh) {
		this.kh = kh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmffb_$kmid$.xm
	 * @return  the value of kmffb_$kmid$.xm
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getXm() {
		return xm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmffb_$kmid$.xm
	 * @param xm  the value for kmffb_$kmid$.xm
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setXm(String xm) {
		this.xm = xm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmffb_$kmid$.jsmc
	 * @return  the value of kmffb_$kmid$.jsmc
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getJsmc() {
		return jsmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmffb_$kmid$.jsmc
	 * @param jsmc  the value for kmffb_$kmid$.jsmc
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setJsmc(String jsmc) {
		this.jsmc = jsmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmffb_$kmid$.ablx
	 * @return  the value of kmffb_$kmid$.ablx
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getAblx() {
		return ablx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmffb_$kmid$.ablx
	 * @param ablx  the value for kmffb_$kmid$.ablx
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setAblx(String ablx) {
		this.ablx = ablx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmffb_$kmid$.ysf
	 * @return  the value of kmffb_$kmid$.ysf
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public BigDecimal getYsf() {
		return ysf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmffb_$kmid$.ysf
	 * @param ysf  the value for kmffb_$kmid$.ysf
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setYsf(BigDecimal ysf) {
		this.ysf = ysf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmffb_$kmid$.ff
	 * @return  the value of kmffb_$kmid$.ff
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public BigDecimal getFf() {
		return ff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmffb_$kmid$.ff
	 * @param ff  the value for kmffb_$kmid$.ff
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setFf(BigDecimal ff) {
		this.ff = ff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kmffb_$kmid$.kmid
	 * @return  the value of kmffb_$kmid$.kmid
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public Integer getKmid() {
		return kmid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kmffb_$kmid$.kmid
	 * @param kmid  the value for kmffb_$kmid$.kmid
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setKmid(Integer kmid) {
		this.kmid = kmid;
	}
}