package com.lanou.entity;

public class Kskmb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kskmb.id
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kskmb.ksid
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private Integer ksid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kskmb.ksmc
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String ksmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kskmb.kmid
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private Integer kmid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kskmb.kmmc
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String kmmc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kskmb.id
	 * @return  the value of kskmb.id
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kskmb.id
	 * @param id  the value for kskmb.id
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kskmb.ksid
	 * @return  the value of kskmb.ksid
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public Integer getKsid() {
		return ksid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kskmb.ksid
	 * @param ksid  the value for kskmb.ksid
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setKsid(Integer ksid) {
		this.ksid = ksid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kskmb.ksmc
	 * @return  the value of kskmb.ksmc
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getKsmc() {
		return ksmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kskmb.ksmc
	 * @param ksmc  the value for kskmb.ksmc
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setKsmc(String ksmc) {
		this.ksmc = ksmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kskmb.kmid
	 * @return  the value of kskmb.kmid
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public Integer getKmid() {
		return kmid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kskmb.kmid
	 * @param kmid  the value for kskmb.kmid
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setKmid(Integer kmid) {
		this.kmid = kmid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kskmb.kmmc
	 * @return  the value of kskmb.kmmc
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getKmmc() {
		return kmmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kskmb.kmmc
	 * @param kmmc  the value for kskmb.kmmc
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setKmmc(String kmmc) {
		this.kmmc = kmmc;
	}
}