package com.lanou.entity;

public class Student {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xsxxb.xjh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String xjh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xsxxb.xxid
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private Integer xxid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xsxxb.xxmc
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String xxmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xsxxb.nj
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String nj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xsxxb.bj
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String bj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xsxxb.kh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String kh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xsxxb.xm
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String xm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xsxxb.xslx1
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String xslx1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xsxxb.xslx2
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	private String xslx2;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xsxxb.xjh
	 * @return  the value of xsxxb.xjh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getXjh() {
		return xjh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xsxxb.xjh
	 * @param xjh  the value for xsxxb.xjh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setXjh(String xjh) {
		this.xjh = xjh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xsxxb.xxid
	 * @return  the value of xsxxb.xxid
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public Integer getXxid() {
		return xxid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xsxxb.xxid
	 * @param xxid  the value for xsxxb.xxid
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setXxid(Integer xxid) {
		this.xxid = xxid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xsxxb.xxmc
	 * @return  the value of xsxxb.xxmc
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getXxmc() {
		return xxmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xsxxb.xxmc
	 * @param xxmc  the value for xsxxb.xxmc
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setXxmc(String xxmc) {
		this.xxmc = xxmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xsxxb.nj
	 * @return  the value of xsxxb.nj
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getNj() {
		return nj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xsxxb.nj
	 * @param nj  the value for xsxxb.nj
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setNj(String nj) {
		this.nj = nj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xsxxb.bj
	 * @return  the value of xsxxb.bj
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getBj() {
		return bj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xsxxb.bj
	 * @param bj  the value for xsxxb.bj
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setBj(String bj) {
		this.bj = bj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xsxxb.kh
	 * @return  the value of xsxxb.kh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getKh() {
		return kh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xsxxb.kh
	 * @param kh  the value for xsxxb.kh
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setKh(String kh) {
		this.kh = kh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xsxxb.xm
	 * @return  the value of xsxxb.xm
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getXm() {
		return xm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xsxxb.xm
	 * @param xm  the value for xsxxb.xm
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setXm(String xm) {
		this.xm = xm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xsxxb.xslx1
	 * @return  the value of xsxxb.xslx1
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getXslx1() {
		return xslx1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xsxxb.xslx1
	 * @param xslx1  the value for xsxxb.xslx1
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setXslx1(String xslx1) {
		this.xslx1 = xslx1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xsxxb.xslx2
	 * @return  the value of xsxxb.xslx2
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public String getXslx2() {
		return xslx2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xsxxb.xslx2
	 * @param xslx2  the value for xsxxb.xslx2
	 * @mbg.generated  Wed Apr 11 16:07:50 CST 2018
	 */
	public void setXslx2(String xslx2) {
		this.xslx2 = xslx2;
	}
}