package com.lanou.mapper;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.Kmcjb;
@MapperScan
public interface KmcjbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kmcjb_$kmid$
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kmcjb_$kmid$
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int insert(Kmcjb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kmcjb_$kmid$
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int insertSelective(Kmcjb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kmcjb_$kmid$
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    Kmcjb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kmcjb_$kmid$
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int updateByPrimaryKeySelective(Kmcjb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kmcjb_$kmid$
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int updateByPrimaryKey(Kmcjb record);
}