package com.lanou.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

import com.lanou.bean.ScoreBean;
import com.lanou.entity.Kmffb;
@MapperScan
public interface KmffbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kmffb_$kmid$
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kmffb_$kmid$
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int insert(Kmffb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kmffb_$kmid$
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int insertSelective(Kmffb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kmffb_$kmid$
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    Kmffb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kmffb_$kmid$
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int updateByPrimaryKeySelective(Kmffb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kmffb_$kmid$
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int updateByPrimaryKey(Kmffb record);
    
    /**
     * 查询单科平均成绩
     * @return
     */
    List<ScoreBean> selectAnAvgScore();
    /**
     * 单科最高成绩
     * @return
     */
    List<ScoreBean> selectAnMaxScore();
    /**
     * 查询单科最低分
     */
    List<ScoreBean>selectAnMinScore();
    /**
     * 单科原始成绩
     * @param xjh
     * @return
     */
    List<ScoreBean>selectAnYuanShiScore(@Param("xjh")String xjh);
}