package com.lanou.mapper;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.Kskmb;
@MapperScan
public interface KskmbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kskmb
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kskmb
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int insert(Kskmb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kskmb
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int insertSelective(Kskmb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kskmb
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    Kskmb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kskmb
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int updateByPrimaryKeySelective(Kskmb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kskmb
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int updateByPrimaryKey(Kskmb record);
}