package com.lanou.mapper;

import java.util.List;
import java.util.Map;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.Student;
@MapperScan
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xsxxb
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int deleteByPrimaryKey(String xjh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xsxxb
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xsxxb
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xsxxb
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    Student selectByPrimaryKey(String xjh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xsxxb
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xsxxb
     *
     * @mbg.generated Wed Apr 11 16:07:50 CST 2018
     */
    int updateByPrimaryKey(Student record);
    /**
	 * 查询所有废品信息
	 * 
	 * @return
	 */
	List<Student> selectAllStudent(Map<String, Object> map);

	/**
	 * 查询废品的总记录数
	 * 
	 * @param map
	 * @return
	 */
	int selectPageStudentCount(Map<String, Object> map);
}